# Generated by Django 6.1.2 on 2026-10-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
